root = "."  
tmp_dir = "tmp"

[build]
  args_bin = []
  bin = "tmp\\main.exe"
  cmd = "go build -o ./tmp/main.exe ./cmd/api"
  delay = 1000
  exclude_dir = ["assets", "tmp", "vendor", "testdata", "./app/frontend"]
  full_bin = "tmp/main"
  include_ext = ["go", "tpl", "tmpl", "html"]


[log]
  time = false
