services:
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"

  frontend:
    build:
      context: ./app/frontend
      target: prod
    depends_on:
      - backend
    ports:
      - "5173:5173"
    networks:
      - curator

  backend:
    build:
      context: ./app/backend
      target: prod
    ports:
      - "8000:8000"
    volumes:
      - ./app/backend:/app
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - curator

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:

networks:
  curator:
    driver: bridge
