services:
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"

  backend:
    build:
      context: ./app/backend
      target: prod
    depends_on:
      - redis
    environment:
      - REDIS_ADDR=redis:6379
      - PORT=3000
    ports:
      - "3000:3000"
    networks:
      - curator

  frontend:
    build:
      context: ./app/frontend
      target: prod
    depends_on:
      - backend
    ports:
      - "5173:5173"
    networks:
      - curator

  python-service:
    build: ./app/python-service
    ports:
      - "5000:5000"
    networks:
      - curator

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:

networks:
  curator:
    driver: bridge
