version: "3"

tasks:
  dev:
    cmds:
      - task: frontend
      - task: backend
    parallel: true

  frontend:
    dir: app/frontend
    cmds:
      - pnpm run dev

  backend:
    dir: app/backend
    cmds:
      - air
