# Watch only backend folder
root = "."
tmp_dir = "tmp"

[build]
  # Build binary to tmp folder (Windows-friendly)
  bin = "tmp/main.exe"
  full_bin = "tmp/main.exe"
  cmd = "go build -o tmp/main.exe ./cmd/api"
  delay = 1000

  # Don't rebuild when frontend or other junk changes
  exclude_dir = [
    "assets",
    "tmp",
    "vendor",
    "testdata",
    "app/frontend"
  ]

  include_ext = ["go", "tpl", "tmpl", "html"]

[log]
  time = false
