# even-better-toml: no-schema
root = "."
tmp_dir = "tmp"

[build]
  # Build binary to tmp folder (Windows-friendly)
  bin = "tmp/main.exe"
  full_bin = "tmp/main.exe"
  cmd = "go build -o tmp/main.exe ."
  delay = 1000

  include_ext = ["go", "tpl", "tmpl", "html"]

[log]
  time = false
